### ISSUE TITLE
`readDataAsString` shadowed by incorrect doc comment

### ISSUE THREAD

**Issue by jacobcarpenter** [pelikhan/sprite-data#1]
The block metadata comment (sorry if wrong terminology) above `readDataAsString` hides the function as a second copy of "Read data as number"

https://github.com/pelikhan/sprite-data/blob/master/main.ts#L41-L48

<img width="398" alt="Screen Shot 2020-04-03 at 9 35 03 AM" src="https://user-images.githubusercontent.com/194333/78384348-df470200-758e-11ea-859c-cb237c74f109.png">

**Comment by pelikhan** [comment]
Fixed.
